### PR TITLE
Node controller should allow grace period for reboot

### PR DESCRIPTION
**Pull request by sjones4**
Node controller maintenance work now allows for reported hypervisor states during instance reboot.

When rebooting, the instance will be in the `BOOTING` state while still running until shutdown is requested. During this time the maintenance thread could detect the instance as `RUNNING` and reset the state. This is prevented by ensuring one `MONITORING_PERIOD` has elapsed between the boot time and a `BOOTING` to `RUNNING` state transition.

Once the instance is shutting down we ignore the reported states of `SHUTOFF` or `SHUTDOWN` until the `NC_REBOOT_GRACE_PERIOD_SEC` (30) has elapsed. This value can be configured in `eucalyptus.conf` in case the default period is too short.

These changes prevent the maintenance work from terminating the instance during reboot.

Fixes corymbia/eucalyptus#117

### CODE REVIEW

**Comment by obino** [comment]
@sjones4 does this needs a demo?

**Comment by sjones4** [comment]
@obino there is not a quick demo for this issue as reliably reproducing can require 100s of instance reboots. As we are impacted by the issue for appscale testing I think the "demo" will be that the issue is addressed for that usage (a custom build with the fix is already in use)

**Comment by sjones4** [comment]
A snapshot build `eucalyptus-nc-4.4.5-0.33.snapshot.20181010.as.el7.x86_64` was deployed for evaluation a while ago, looks like it has prevented some instance terminations:

```
192.168.111.52:
2018-11-13 22:00:07  INFO | [i-2ea9b91a] ignoring hypervisor reported state Shutdown for booting domain during grace period (30)
192.168.111.54:
2018-10-24 04:39:20  INFO | [i-399abfaa] ignoring hypervisor reported state Shutdown for booting domain during grace period (30)
2018-10-26 12:50:18  INFO | [i-478ee1a2] ignoring hypervisor reported state Shutdown for booting domain during grace period (30)
192.168.111.56:
2018-11-14 21:45:23  INFO | [i-597ef2a4] ignoring hypervisor reported state Shutdown for booting domain during grace period (30)
```

**Comment by sjones4** [comment]
build, deploy, test:
https://ocd.appscale.com:8080/job/eucalyptus-internal-44-build-random-rpms/38/
https://ocd.appscale.com:8080/job/eucalyptus-44-qa-deploy/285/
https://ocd.appscale.com:8080/job/eucalyptus-44-qa-suite/94/

**Pull request merged**
