### PR TITLE
Set umask consistently for thread safety

### PR DESCRIPTION
**Pull request by sjones4**
Node controller now uses a standard 0022 umask.

This pull request fixes Corymbia/eucalyptus#20

### CODE REVIEW

**Comment by dmitrii** [comment]
Agree that pair-wise umask() usage is not thread-safe and, looks like, results in bad NC failures. So this would be great to fix. But I have a couple concerns with the proposed fix:

If umask() is only ever to be used with one constant value, we might as well call it once at startup and that's it. The proposed 0022 is the default, so we may be able to simply remove all umask() invocations and unused constants (LOG_FILE_PERM). Or we could set it outside the NC in a shell init file?

However, with 0022 we may get some files and directories with rw-r--r-- permissions, which is too open for most files created by NC, I think. I say some because other created files should be based off of BLOBSTORE_FILE_PERM and BACKING_FILE_PERM constants, which are both 660 (resulting in rw-rw----).

So, is there one umask value that will work for all use cases and will be sufficiently restrictive? The only other value I see used in the code is #define LOG_FILE_PERM 0640 which further constrains the mask (removing the 'w' bit for group). I don't think that is a crucial difference as our user/group is always eucalyptus/eucalyptus. So, I suspect we can set umask to 0006 once (either in NC or in shell), to prevent any of our helpers from preventing world-accessible files, and remove all of the pair-wise uses of umask altogether.

**Comment by sjones4** [comment]
These are the permissions for instances before / after the fix:

4.4.2:

```
# ll ./AIDAAMMB7XLP6WLHFGZFU/i-e88ec84c ./AIDAAMMB7XLP6WLHFGZFU
./AIDAAMMB7XLP6WLHFGZFU:
total 4
drwx--x--x. 2 eucalyptus eucalyptus   20 Mar 12 14:37 i-67f7e66d
drwx--x--x. 2 eucalyptus eucalyptus 4096 Mar 12 14:53 i-e88ec84c

./AIDAAMMB7XLP6WLHFGZFU/i-e88ec84c:
total 479576
-rw-------. 1 qemu       qemu            66192 Mar 12 14:55 console.log
-rw-r-----. 1 eucalyptus eucalyptus 2147483648 Mar 15 16:51 emi-b71fbef7-14e248fa.blocks
-rw-r-----. 1 eucalyptus eucalyptus         77 Mar 12 14:52 emi-b71fbef7-14e248fa.deps
-rw-r-----. 1 eucalyptus eucalyptus        196 Mar 12 14:52 emi-b71fbef7-14e248fa.dm
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 12 14:52 emi-b71fbef7-14e248fa.lock
-rw-r-----. 1 eucalyptus eucalyptus         10 Mar 12 14:52 emi-b71fbef7-14e248fa.loopback
-rw-r-----. 1 eucalyptus eucalyptus         21 Mar 12 14:52 emi-b71fbef7-14e248fa.sig
-rwx------. 1 qemu       qemu          1474560 Mar 12 14:52 floppy
-rw-r--r--. 1 eucalyptus eucalyptus       1691 Mar 12 14:53 instance-libvirt.xml
-rw-rw----. 1 eucalyptus eucalyptus       7313 Mar 15 16:51 instance.xml
lrwxrwxrwx. 1 eucalyptus eucalyptus         71 Mar 12 14:52 link-to-vda -> /dev/mapper/euca-AIDAAMMB7XLP6WLHFGZFU-i-e88ec84c-emi-b71fbef7-14e248fa
lrwxrwxrwx. 1 eucalyptus eucalyptus         72 Mar 12 14:53 link-to-vdb -> /dev/mapper/euca-AIDAAMMB7XLP6WLHFGZFU-i-e88ec84c-prt-08192ext3-8c587647
-rw-r-----. 1 eucalyptus eucalyptus 8589934592 Mar 12 14:55 prt-08192ext3-8c587647.blocks
-rw-r-----. 1 eucalyptus eucalyptus        199 Mar 12 14:52 prt-08192ext3-8c587647.dm
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 12 14:53 prt-08192ext3-8c587647.lock
-rw-r-----. 1 eucalyptus eucalyptus         10 Mar 12 14:52 prt-08192ext3-8c587647.loopback
-rw-r-----. 1 eucalyptus eucalyptus         37 Mar 12 14:52 prt-08192ext3-8c587647.sig
```

4.4.3:

```
# ll ./AIDAAXX4PJASCD5H7XTUY ./AIDAAXX4PJASCD5H7XTUY/i-e76300fc
./AIDAAXX4PJASCD5H7XTUY:
total 4
drwx--x--x. 2 eucalyptus eucalyptus 4096 Mar 12 15:38 i-e76300fc

./AIDAAXX4PJASCD5H7XTUY/i-e76300fc:
total 432688
-rw-------. 1 qemu       qemu            72592 Mar 12 15:39 console.log
-rw-r-----. 1 eucalyptus eucalyptus 2147483648 Mar 15 16:52 emi-d7c588fa-14e248fa.blocks
-rw-r-----. 1 eucalyptus eucalyptus         77 Mar 12 15:37 emi-d7c588fa-14e248fa.deps
-rw-r-----. 1 eucalyptus eucalyptus        196 Mar 12 15:37 emi-d7c588fa-14e248fa.dm
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 12 15:37 emi-d7c588fa-14e248fa.lock
-rw-r-----. 1 eucalyptus eucalyptus         10 Mar 12 15:37 emi-d7c588fa-14e248fa.loopback
-rw-r-----. 1 eucalyptus eucalyptus         21 Mar 12 15:37 emi-d7c588fa-14e248fa.sig
-rwx------. 1 qemu       qemu          1474560 Mar 12 15:37 floppy
-rw-r--r--. 1 eucalyptus eucalyptus       1940 Mar 12 15:37 instance-libvirt.xml
-rw-rw----. 1 eucalyptus eucalyptus       7285 Mar 15 16:52 instance.xml
lrwxrwxrwx. 1 eucalyptus eucalyptus         71 Mar 12 15:37 link-to-vda -> /dev/mapper/euca-AIDAAXX4PJASCD5H7XTUY-i-e76300fc-emi-d7c588fa-14e248fa
lrwxrwxrwx. 1 eucalyptus eucalyptus         72 Mar 12 15:37 link-to-vdb -> /dev/mapper/euca-AIDAAXX4PJASCD5H7XTUY-i-e76300fc-prt-08192ext3-8c587647
-rw-r-----. 1 eucalyptus eucalyptus 8589934592 Mar 12 15:40 prt-08192ext3-8c587647.blocks
-rw-r-----. 1 eucalyptus eucalyptus        199 Mar 12 15:37 prt-08192ext3-8c587647.dm
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 12 15:37 prt-08192ext3-8c587647.lock
-rw-r-----. 1 eucalyptus eucalyptus         10 Mar 12 15:37 prt-08192ext3-8c587647.loopback
-rw-r-----. 1 eucalyptus eucalyptus         37 Mar 12 15:37 prt-08192ext3-8c587647.sig
```

And for the cache:

4.4.2:

```
# ll . emi-4cbefb49-1747ce9e
.:
total 0
drwxrwx--x. 2 eucalyptus eucalyptus 55 Mar 12 18:10 emi-2bfaed56-29607e33
drwxrwx--x. 2 eucalyptus eucalyptus 55 Mar 14 09:16 emi-4cbefb49-1747ce9e
drwxrwx--x. 2 eucalyptus eucalyptus 71 Mar 12 14:44 emi-b71fbef7-14e248fa

emi-4cbefb49-1747ce9e:
total 8388612
-rw-r-----. 1 eucalyptus eucalyptus 8589934592 Mar 12 14:46 blocks
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 14 08:56 lock
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 14 09:16 refs
-rw-r-----. 1 eucalyptus eucalyptus         21 Mar 12 14:43 sig
```

4.4.3:

```
# ll . emi-21459a09-1747ce9e
.:
total 0
drwxrwx--x. 2 eucalyptus eucalyptus 55 Mar 14 09:16 emi-21459a09-1747ce9e
drwxrwx--x. 2 eucalyptus eucalyptus 55 Mar 12 18:10 emi-cfe6fc99-29607e33
drwxrwx--x. 2 eucalyptus eucalyptus 71 Mar 12 15:37 emi-d7c588fa-14e248fa

emi-21459a09-1747ce9e:
total 8388612
-rw-r-----. 1 eucalyptus eucalyptus 8589934592 Mar 12 15:41 blocks
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 14 08:55 lock
-rw-r-----. 1 eucalyptus eucalyptus          0 Mar 14 09:16 refs
-rw-r-----. 1 eucalyptus eucalyptus         21 Mar 12 15:39 sig
```

i.e. there is no change.

**Comment by dmitrii** [comment]
Okay, that's good. What about /var/log/eucalyptus files? (Not that they're super-sensitive.)

At this point I'd be tempted to remove umask() calls altogether. That's the cleanest solution. Not insisting on this, but if it's easy to try out...

**Comment by sjones4** [comment]
Permissions on log (etc) files were more open (644) than in 4.4.2 (640) with this pull request.

I looked at updating the current fix to address the more open permissions and also tried with a 0026 umask:

https://github.com/sjones4/eucalyptus/commits/topic-integration-umask-0022
https://github.com/sjones4/eucalyptus/commits/topic-integration-umask-0026

Checking the file permissions with those changes in place the 0022 umask looks correct but the 0026 has more restrictive permissions on some files:

```
< 644 /run/eucalyptus/eucalyptus-cluster.pid
< 644 /run/eucalyptus/eucalyptus-node.pid
---
> 640 /run/eucalyptus/eucalyptus-cluster.pid
> 640 /run/eucalyptus/eucalyptus-node.pid
...
< 644 /run/eucalyptus/global_network_info.xml
< 644 /run/eucalyptus/httpd-cc.conf
< 644 /run/eucalyptus/httpd-nc.conf
---
> 600 /run/eucalyptus/global_network_info.xml
> 640 /run/eucalyptus/httpd-cc.conf
> 640 /run/eucalyptus/httpd-nc.conf
...
< 644 /run/eucalyptus/net/edge_netmeter
< 644 /run/eucalyptus/net/edge_netmeter_done
< 644 /run/eucalyptus/net/euca-dhcp.conf
---
> 640 /run/eucalyptus/net/edge_netmeter
> 640 /run/eucalyptus/net/edge_netmeter_done
> 640 /run/eucalyptus/net/euca-dhcp.conf
...
< 644 /var/log/eucalyptus/axis2c.log
---
> 640 /var/log/eucalyptus/axis2c.log
...
< 644 /var/log/eucalyptus/httpd-cluster_error_log
< 644 /var/log/eucalyptus/httpd-node_error_log
---
> 640 /var/log/eucalyptus/httpd-cluster_error_log
> 640 /var/log/eucalyptus/httpd-node_error_log
```

Basic tests passed for both umask branches, I haven't run full tests yet.

My preference would be to keep the 0022 umask and ensure that file permissions are identical to those in 4.4.2 (or at least as close a possible), i.e. add the changes in topic-integration-umask-0022 to this pull request.

**Comment by sjones4** [comment]
Updated this pull request with explicit permissions for some files where umask 0022 results in permissions being more open than in 4.4.2.

Since the pull request is updated approval is needed for merging.

**Pull request merged**
